# Generated by Django 5.0.7 on 2024-07-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_song_audio_metadata_alter_album_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_metadata',
        ),
    ]
