# Generated by Django 5.0.7 on 2024-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_song_audio_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
