# Generated by Django 5.0.7 on 2024-07-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_artist_alter_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='producers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
