# Generated by Django 5.0.7 on 2024-07-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_album_year_song_comment_song_producers_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
