# Generated by Django 5.0.7 on 2024-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_song_audio_file_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='video_url',
        ),
        migrations.AddField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
        migrations.AddField(
            model_name='song',
            name='video_file_1',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
