# Generated by Django 5.0.7 on 2024-09-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_song_video_url_song_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
